apiVersion: v1
kind: Secret
metadata:
  name: ferro-secret
  namespace: ferro
  labels:
    app.kubernetes.io/name: ferro
    app.kubernetes.io/part-of: ferro
type: Opaque
data:
  FERRO_ADMIN_USER: YWRtaW4=
  FERRO_ADMIN_PASSWORD: Y2hhbmdlbWU=
  # Generate with: openssl rand -hex 32 | base64
  FERRO_WOPI_TOKEN_SECRET: ZGVmYXVsdC10b2tlbi1zZWNyZXQtY2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=
