apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ferro.fullname" . }}
  labels:
    {{- include "ferro.labels" . | nindent 4 }}
type: Opaque
data:
  FERRO_ADMIN_USER: {{ .Values.auth.adminUser | b64enc | quote }}
  FERRO_ADMIN_PASSWORD: {{ .Values.auth.adminPassword | b64enc | quote }}
  {{- if .Values.config.wopiTokenSecret }}
  FERRO_WOPI_TOKEN_SECRET: {{ .Values.config.wopiTokenSecret | b64enc | quote }}
  {{- end }}
