global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ferro-server'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ferro-server:8080']
        labels:
          instance: 'ferro-server'
          app: 'ferro'
