[alias]
xt = "test --workspace --locked"
xc = "clippy --workspace --all-targets --locked -- -D warnings"
xf = "fmt --all -- --check"
cov = "tarpaulin --workspace --all-features --skip-clean --out Html --output-dir coverage"
cov-ci = "tarpaulin --workspace --all-features --skip-clean --out Xml --output-dir coverage"
